language: objective-c
before_install:
- gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project ARAlertController.xcodeproj -scheme ARAlertController test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
